#--------------------------------------------------------------------------

# development:
#     storage: 's3' #:s3
#     path: ":attachment/:uuid/:style/:filename"
#     url: ":s3_domain_url/:attachment/:uuid/:style/:filename"
    
development:
    storage: 'filesystem' #:filesystem
    path: ":rails_root/public/system/:attachment/:uuid/:style/:filename"
    url: "/system/:attachment/:uuid/:style/:filename"

#--------------------------------------------------------------------------
    
test:
    storage: 'filesystem'
    path: ":rails_root/public/system/:attachment/:uuid/:style/:filename"
    url: "/system/:attachment/:uuid/:style/:filename"

#--------------------------------------------------------------------------

# staging:
#     storage: 'filesystem'
#     path: ":rails_root/public/system/:attachment/:uuid/:style/:filename"
#     url: "/system/:attachment/:uuid/:style/:filename"
    
staging:
    storage: 's3' #:s3
    path: ":attachment/:uuid/:style/:filename"
    url: ":s3_domain_url/:attachment/:uuid/:style/:filename"

#--------------------------------------------------------------------------
        
# production:
#     storage: 'filesystem'
#     path: ":rails_root/public/system/:attachment/:uuid/:style/:filename"
#     url: "/system/:attachment/:uuid/:style/:filename"
        
production:
    storage: 's3' #:s3
    path: ":attachment/:uuid/:style/:filename"
    url: ":s3_domain_url/:attachment/:uuid/:style/:filename"

#--------------------------------------------------------------------------
